"""ReminderWorker sends medication reminders as they come due. Reuses the
same EmailService/retry semantics as notifications, keyed off
MedicationReminder rows generated by reminder_service at prescription time.
"""
import logging

from app.core.db import session_scope
from app.models.base import NotificationStatus
from app.models.identity import Patient, User
from app.models.messaging import MedicationReminder
from app.models.scheduling import Prescription
from app.services.email_service import EmailPermanentError, EmailTransientError, get_email_provider
from app.utils.timeutils import utcnow
from app.workers.celery_app import celery_app

logger = logging.getLogger("reminder_worker")


@celery_app.task(name="app.workers.reminder_worker.send_medication_reminder_task", bind=True)
def send_medication_reminder_task(self, reminder_id: str) -> None:
    with session_scope() as db:
        reminder = db.get(MedicationReminder, reminder_id)
        if not reminder or reminder.status == NotificationStatus.SENT:
            return

        prescription = db.get(Prescription, reminder.prescription_id)
        patient = db.get(Patient, reminder.patient_id)
        user = db.get(User, patient.user_id)

        reminder.attempt_count += 1
        provider = get_email_provider()
        body = (
            f"Reminder: take {prescription.medicine_name} ({prescription.dosage}).\n"
            f"Instructions: {prescription.instructions or 'As directed.'}"
        )
        try:
            provider.send(user.email, "Medication reminder", body)
            reminder.status = NotificationStatus.SENT
            reminder.sent_at = utcnow()
        except EmailPermanentError as e:
            reminder.status = NotificationStatus.FAILED
            reminder.last_error = str(e)
        except EmailTransientError as e:
            reminder.last_error = str(e)
            if reminder.attempt_count >= 5:
                reminder.status = NotificationStatus.FAILED
            # else leave as PENDING; will be retried on next scheduler pass


@celery_app.task(name="app.workers.reminder_worker.process_due_reminders_task")
def process_due_reminders_task(batch_size: int = 200) -> int:
    with session_scope() as db:
        now = utcnow()
        due = db.query(MedicationReminder).filter(
            MedicationReminder.status == NotificationStatus.PENDING,
            MedicationReminder.scheduled_at <= now,
        ).limit(batch_size).all()
        ids = [r.id for r in due]

    for reminder_id in ids:
        send_medication_reminder_task.delay(reminder_id)
    return len(ids)
